repo = "http://10.124.128.2:8888/muses/union-design-h5.git"
users = ["jc-dengp", "jc-lvhj"]
emails = ["jc-dengp@chinaunicom.cn", "jc-lvhj@chinaunicom.cn"]
passwords = ["Tianti%402019", "Tianti%402019"]
